apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.name }}-service
spec:
  selector:
    app: {{ .Values.application.name }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 8080
  type: LoadBalancer